name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - feat  # หรือสาขาที่คุณต้องการให้ deploy อัตโนมัติ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools  # ขั้นตอนติดตั้ง Firebase CLI

    - name: Deploy to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT > serviceAccount.json
        firebase deploy --only hosting

    - name: Display working directory
      run: pwd

    - name: List files
      run: ls -la
