name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - feat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Display working directory
      run: pwd

    - name: List files in Portfolio_Poramin/firebase_application
      run: |
        cd Portfolio_Poramin/firebase_application
        ls -la

    - name: Deploy Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo serviceAccount.json
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > serviceAccount.json
        cd Portfolio_Poramin/firebase_application
        firebase deploy --only hosting --project portfolioporamin
